WebCoreUI/Controllers/AdminController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebCoreUI.Controllers
{  
   [Authorize(Roles ="admin")]

    //Rolü Admin olan buradaki actionları çalıştırabilir
    public class AdminController : Controller
    {
        IUserService _userService;

        public AdminController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult AdminProfile()
        {
            return View();
        }        
    }
}

WebCoreUI/Controllers/ProductListController.cs
using Business.Abstract;
using Entities.DTOs;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Entities.Concrete;
using Microsoft.EntityFrameworkCore;


namespace WebCoreUI.Controllers
{
    public class ProductListController : Controller
    {
        IProductListService _productListService;
     
        public ProductListController(IProductListService productListService)
        {
            _productListService = productListService;
          
        }
        public IActionResult UserProfile()
        {
            return View();
        }
        //Yeni Alışveriş Listesi Ekleme form ekranı metotu
        [HttpGet]
        public IActionResult Create()
        {        
            return View("ProductListCreateForm", new ProductListDto());
        }

        //Yeni Alışveriş Listesi Ekleme metotu
        [HttpPost]
        public IActionResult Create(ProductListDto addproductListDto)
        {
            //Claimdeki Id yi almak istersek:   
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            _productListService.AddProductListDto(addproductListDto,userId);
            return RedirectToAction(nameof(ProductListByUserId));
        }

        //Hangi kullanıcı login olduysa onun Alışveriş listelerini gösteren method
        public IActionResult ProductListByUserId()
        {
            string emailForClaim = User.FindFirstValue("Email");   //Email bilgisini direk cookieden alırız
            var response = _productListService.GetProductListDetailByEmail(emailForClaim).Data;

            return View(response);

            //Claimdeki Id yi almak istesydik:   
            //int userId=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        }

        //AlışVerişListesi içindeki ürünleri gösteren method
        public IActionResult ProductListShowInside(int productListId)
        {
            var response = _productListService.GetProductListInsideShowWithProductName(productListId).Data;
            ViewBag.ProductListId=productListId;
            return View(response);
        }

        //AlışVerişListesinin içine Ürünlistesinden ürün ekleme Ekranı
        [HttpGet]
        public IActionResult ProductAddFromProductList(int productListId)
        {
            //Formun içinden eklemeyeceksin ürünler listesinden ekleyeceksin
            //ViewBag.Categories = _productListService.GetBySelectListCategory().Data;
           
            //Alışveriş listesi içinden tüm ürünleri gösteren method
            ViewBag.ProductListId = productListId;

            return View(_productListService.GetProductShowFromProductList().Data);

        }

        //AlışVerişListesinin içine Ürünlistesinden ürün ekleme       
        public IActionResult ProductAdd(int productListId, int productId)
        {
            
            ViewBag.ProductListId = productListId;

            //Claimdeki Id yi almak istersek:   
            int userId=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            _productListService.AddProductListItem(productListId,productId,userId);

            return RedirectToAction( nameof(ProductListShowInside), productListId);


        }
        public IActionResult ProductDeleteFromProductList(int productListId,int productId)
        {
            ViewBag.ProductListId = productListId;

            //Claimdeki Id yi alrız:   
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            _productListService.DeletedProductListItem( productId, productListId, userId);
            return RedirectToAction(nameof(ProductListShowInside), ViewBag.ProductListId);
        }
        //Alışveriş listesinde Alışverişe Çıkıyorum checkboxı işaretlenince Ajaxın post isteğiyle geldiği action
        [HttpPost]
        public async Task<string> SaveCheckbox(int productListIdSelected, bool shopGoSelected)
        {
            var changeproductList = _productListService.ProductListShopGoSelected(productListIdSelected, shopGoSelected);
           
            if (changeproductList == null)
            {
                return "Hata oluştu";
            }                      
            return "Güncelleme başarılı";
        }

        //Alışveriş listesinin içinde Aldım checkboxı işaretlendiğnde Ajaxın post isteğiyle geldiği action
        [HttpPost]
        public async Task<string> SaveIsItBuyCheckbox(int productListIdSelected, int productIdSelected,bool isItBuySelected)
        {
            ViewBag.ProductListId = productListIdSelected;
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var changeproductList = _productListService.UpdatedProductListItem(productIdSelected, productListIdSelected, userId, isItBuySelected);

            if (changeproductList == null)
            {
                return "Hata oluştu";
            }
            return "Güncelleme başarılı";
        }     
    }
}
    

WebCoreUI/Controllers/UserController.cs
using Business.Abstract;
using Core.Utilities.Results;
using Entities.DTOs;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebCoreUI.Models;

namespace WebCoreUI.Controllers
{
   [Authorize]
    public class UserController : Controller
    {
        IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult List()
        {
            return View(_userService.GetUserLists().Data);

        }
        //Yeni Kullanıcı FormEkranı
        [HttpGet]
        public IActionResult Create()
        {
            return View("UserForm", new UserDetailRegisterDto());
        }

        [HttpPost]
        public IActionResult Create(UserDetailRegisterDto userAdd)
        {          
            _userService.AddUserDto(userAdd);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public IActionResult Edit(int userId)
        {
            //var user=_userService.GetById(userId).Data;
            var user = _userService.GetByUserIdDto(userId).Data;
            return View("UserEditForm", user);
        }
        [HttpPost]
        public IActionResult Edit(UserEditDto userEdit)
        {
            _userService.EditUserDto(userEdit);
            return RedirectToAction(nameof(List));
        }

        public IActionResult Delete(int userId)
        {
            _userService.DeleteUserDto(userId);
            return RedirectToAction(nameof(List));
        }

        //ÜyeGirişi Formu
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Login(UserLoginDto model)
        {
            
            if (ModelState.IsValid)
            {
                //Mail ve şifre eşleşiyor mu
                var existUser = _userService.GetByLoginFilter(model).Data;

                //Claims listesi oluşturp cookide neleri tutulacağı tanımlandı
                //ClaimTypes.... diyerek hazır claim nesnelerinde tutar
                List<Claim> claims = new List<Claim>(); 
                claims.Add(new Claim(ClaimTypes.NameIdentifier, existUser.UserId.ToString()));
                claims.Add(new Claim("Email", existUser.Email));
                claims.Add(new Claim(ClaimTypes.Role, existUser.Role));

                //ClaimsIdentity nesnesi içerisine claimleri ekliyor.Hangi Authentication ı kullanılıyorsa onu da parametre olarak verilir//CookieAuthentication
                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme
                    );
                //ClaimsPrincipal bizden ClaimsIdentity nesnemizi ister
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        //ÜyeOl formu
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Register(UserDetailRegisterDto model)
        {
            if (ModelState.IsValid)
            {                    
                _userService.AddUserDto(model);
                return RedirectToAction(nameof(Login));
            }
            //hata varsa View a verileri geri gönder hatasını görsün
            ModelState.AddModelError("", "Kullanıcı üye olma işlemi gerçekleşmedi");
            return View(model);
            
        }
     
        //public IActionResult Profile()
        //{
        //    return View();
        //}
        
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);  //Cookieyi kapat
            return RedirectToAction(nameof(Login));
        }

    }
}

WebCoreUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCoreUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/WebCoreUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCoreUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">AnaSayfa</a>
                        </li>

                        @if (User.Identity.IsAuthenticated) //User propertsindeki ıdentitye ulaşıp IsAuthenticated mi diye bakarız
                        {
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminProfile"><i class="fa-solid fa-user me-2"></i>Admin</a>
                                </li>
                            }
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductList" asp-action="UserProfile"><i class="fa-solid fa-user me-2"></i>@User.FindFirst("Email").Value </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
                            </li>
                           
                        }
                        else
                        {

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>Giriş Yap</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register"><i class="fa-solid fa-user me-2"></i>Üye Ol</a>
                            </li>                           
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebCoreUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>